server:
  port: 8085
  servlet:
    context-path: /chat-ai
spring:
  application:
    name: chat-ai-service
  cloud:
    openfeign:
      client:
        config:
          # Timeout mặc định cho tất cả Feign client
          default:
            connect-timeout: 60000
            read-timeout: 120000
          gemini-service:
            url: ${FEIGN_GEMINI:http://gemini-service:5001/gemini}
            connect-timeout: 30000
            read-timeout: 60000
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mariadb://mariadb:3306/chat_ai_db}
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:sapassword}
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/chat/completions
        options:
          model: gemini-2.5-flash-lite
          temperature: 0.3
          # Thêm các options này để force tool calling
          max-tokens: 500
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always